# Generated by Django 4.1 on 2022-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('gender', models.CharField(choices=[('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('DevOps', 'DevOps'), ('AWS', 'AWS'), ('ITF', 'ITF')], max_length=50)),
            ],
        ),
    ]
